import type { DbOrder, DbPaymentRecord, DbSquareLink } from "../../schema";
import { RuntimeSeedDates, toDateTimeString, withOffset } from "../support";

export function createPayments({ baseDate }: RuntimeSeedDates): DbPaymentRecord[] {
  return [
    {
      id: "pay-9001",
      orderId: "order-9001",
      source: "square",
      status: "captured",
      amount: 747.5,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 10, 0)),
      squarePaymentId: "sq_pay_9001",
    },
    {
      id: "pay-9002",
      orderId: "order-9002",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9003",
      orderId: "order-9003",
      source: "square",
      status: "captured",
      amount: 1080,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 11, 30)),
      squarePaymentId: "sq_pay_9003",
    },
    {
      id: "pay-9004",
      orderId: "order-9004",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9005",
      orderId: "order-9005",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9006",
      orderId: "order-9006",
      source: "square",
      status: "captured",
      amount: 747.5,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 10, 30)),
      squarePaymentId: "sq_pay_9006",
    },
    {
      id: "pay-9007",
      orderId: "order-9007",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9008",
      orderId: "order-9008",
      source: "square",
      status: "captured",
      amount: 950,
      collectedAt: toDateTimeString(withOffset(baseDate, -4, 14, 0)),
      squarePaymentId: "sq_pay_9008",
    },
    {
      id: "pay-9009",
      orderId: "order-9009",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9010",
      orderId: "order-9010",
      source: "square",
      status: "captured",
      amount: 600,
      collectedAt: toDateTimeString(withOffset(baseDate, -6, 10, 45)),
      squarePaymentId: "sq_pay_9010",
    },
    {
      id: "pay-9011",
      orderId: "order-9011",
      source: "square",
      status: "captured",
      amount: 800,
      collectedAt: toDateTimeString(withOffset(baseDate, -3, 12, 0)),
      squarePaymentId: "sq_pay_9011",
    },
    {
      id: "pay-9012",
      orderId: "order-9012",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9013",
      orderId: "order-9013",
      source: "square",
      status: "captured",
      amount: 1695,
      collectedAt: "2026-02-26T15:00:00",
      squarePaymentId: "sq_pay_9013",
    },
    {
      id: "pay-8821",
      orderId: "order-8821",
      source: "square",
      status: "captured",
      amount: 1495,
      collectedAt: "2026-02-28T14:00:00",
      squarePaymentId: "sq_pay_8821",
    },
    {
      id: "pay-8610",
      orderId: "order-8610",
      source: "square",
      status: "captured",
      amount: 65,
      collectedAt: "2026-01-17T12:00:00",
      squarePaymentId: "sq_pay_8610",
    },
    {
      id: "pay-8443",
      orderId: "order-8443",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8904",
      orderId: "order-8904",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8732",
      orderId: "order-8732",
      source: "square",
      status: "captured",
      amount: 95,
      collectedAt: "2026-02-12T13:30:00",
      squarePaymentId: "sq_pay_8732",
    },
    {
      id: "pay-8940",
      orderId: "order-8940",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8528",
      orderId: "order-8528",
      source: "square",
      status: "captured",
      amount: 35,
      collectedAt: "2026-01-08T12:00:00",
      squarePaymentId: "sq_pay_8528",
    },
    {
      id: "pay-9014",
      orderId: "order-9014",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9015",
      orderId: "order-9015",
      source: "square",
      status: "captured",
      amount: 800,
      collectedAt: toDateTimeString(withOffset(baseDate, -3, 15, 30)),
      squarePaymentId: "sq_pay_9015",
    },
    {
      id: "pay-9016",
      orderId: "order-9016",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9017",
      orderId: "order-9017",
      source: "square",
      status: "captured",
      amount: 150,
      collectedAt: toDateTimeString(withOffset(baseDate, -1, 13, 20)),
      squarePaymentId: "sq_pay_9017",
    },
    {
      id: "pay-9018",
      orderId: "order-9018",
      source: "square",
      status: "captured",
      amount: 1795,
      collectedAt: "2026-02-26T14:10:00",
      squarePaymentId: "sq_pay_9018",
    },
    {
      id: "pay-9019",
      orderId: "order-9019",
      source: "square",
      status: "captured",
      amount: 900,
      collectedAt: toDateTimeString(withOffset(baseDate, -2, 16, 35)),
      squarePaymentId: "sq_pay_9019",
    },
    {
      id: "pay-9020",
      orderId: "order-9020",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9021",
      orderId: "order-9021",
      source: "square",
      status: "captured",
      amount: 1495,
      collectedAt: "2026-02-19T14:05:00",
      squarePaymentId: "sq_pay_9021",
    },
    {
      id: "pay-9022",
      orderId: "order-9022",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9023",
      orderId: "order-9023",
      source: "square",
      status: "captured",
      amount: 750,
      collectedAt: toDateTimeString(withOffset(baseDate, -5, 14, 30)),
      squarePaymentId: "sq_pay_9023",
    },
  ];
}

export function createSquareLinks(orders: DbOrder[]): DbSquareLink[] {
  return orders.map((order) => ({
    orderId: order.id,
    squareOrderId: `sq_order_${order.displayId.toLowerCase()}`,
  }));
}
