import type { PickupLocation } from "../types";
import type {
  DbAirtableLink,
  DbCustomer,
  DbCustomerEvent,
  DbLocation,
  DbMeasurementSet,
  DbOrder,
  DbOrderScope,
  DbOrderScopeLine,
  DbPaymentRecord,
  DbPickupAppointment,
  DbPickupNotification,
  DbServiceAppointment,
  DbSquareLink,
  PrototypeDatabase,
} from "./schema";

function toDateString(date: Date) {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, "0");
  const day = `${date.getDate()}`.padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function toDateTimeString(date: Date) {
  return `${toDateString(date)}T${`${date.getHours()}`.padStart(2, "0")}:${`${date.getMinutes()}`.padStart(2, "0")}:00`;
}

function withOffset(base: Date, days: number, hours = 12, minutes = 0) {
  const next = new Date(base);
  next.setHours(hours, minutes, 0, 0);
  next.setDate(next.getDate() + days);
  return next;
}

function withMinuteDelta(base: Date, minutes: number) {
  const next = new Date(base);
  next.setSeconds(0, 0);
  next.setMinutes(next.getMinutes() + minutes);
  return next;
}

function createLocationId(location: PickupLocation) {
  return `loc_${location.toLowerCase().replace(/\s+/g, "_")}`;
}

const baseValues = {
  "Back Length": "30",
  Shoulder: "18",
  Chest: "40.5",
  Stomach: "35.5",
  Seat: "39.5",
  Bicep: "14",
  "Sleeve Length": "25",
  Neck: "15.5",
  Waist: "34",
  Thigh: "23.5",
  Bottom: "15.5",
  Rise: "11",
  Length: "41.25",
  "Shirt Cuff Left": "8",
  "Shirt Cuff Right": "8",
};

const davidValues = {
  "Back Length": "29",
  Shoulder: "17.5",
  Chest: "38.5",
  Stomach: "33",
  Seat: "37.5",
  Bicep: "13.5",
  "Sleeve Length": "24.75",
  Neck: "15",
  Waist: "32",
  Thigh: "22.75",
  Bottom: "14.75",
  Rise: "10.75",
  Length: "40.25",
  "Shirt Cuff Left": "7.75",
  "Shirt Cuff Right": "7.75",
};

const andreaValues = {
  ...baseValues,
  Shoulder: "16.5",
  Chest: "36.5",
  Waist: "29.5",
  Seat: "38.25",
  "Sleeve Length": "23.75",
  Length: "40.75",
};

const priyaValues = {
  ...baseValues,
  Shoulder: "17",
  Chest: "37.75",
  Waist: "30.25",
  Seat: "39",
  "Sleeve Length": "24",
  Length: "41",
};

const sofiaValues = {
  ...baseValues,
  Shoulder: "16.75",
  Chest: "35.75",
  Waist: "28.75",
  Seat: "37.5",
  "Sleeve Length": "23.5",
  Length: "40.5",
};

export function createPrototypeDatabase(referenceDate = new Date()): PrototypeDatabase {
  const liveReference = new Date(referenceDate);
  liveReference.setSeconds(0, 0);
  const baseDate = new Date(referenceDate);
  baseDate.setHours(12, 0, 0, 0);

  const locations: DbLocation[] = [
    { id: createLocationId("Fifth Avenue"), name: "Fifth Avenue" },
    { id: createLocationId("Queens"), name: "Queens" },
    { id: createLocationId("Long Island"), name: "Long Island" },
  ];

  const customers: DbCustomer[] = [
    {
      id: "C-1042",
      name: "James Carter",
      phone: "(555) 201-9044",
      email: "james.carter@example.com",
      address: "14 E 61st St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Feb 28",
      measurementsStatus: "on_file",
      notes: "Prefers slim fit",
      isVip: true,
    },
    {
      id: "C-1078",
      name: "Maria Ellis",
      phone: "(555) 884-7712",
      email: "maria.ellis@example.com",
      address: "22-18 33rd Ave, Astoria, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 10",
      measurementsStatus: "missing",
      notes: "Wedding party order",
    },
    {
      id: "C-1116",
      name: "David Nguyen",
      phone: "(555) 490-1162",
      email: "d.nguyen@example.com",
      address: "48 Harbor Ln, Huntington, NY",
      preferredLocationId: createLocationId("Long Island"),
      lastVisitLabel: "Mar 14",
      measurementsStatus: "on_file",
      notes: "Rush alterations",
    },
    {
      id: "C-1124",
      name: "Andrea Brooks",
      phone: "(555) 331-2088",
      email: "andrea.brooks@example.com",
      address: "117 W 58th St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Mar 12",
      measurementsStatus: "on_file",
      notes: "Bridal party tailoring",
    },
    {
      id: "C-1135",
      name: "Noah Bennett",
      phone: "(555) 771-0031",
      email: "noah.bennett@example.com",
      address: "31-22 Crescent St, Astoria, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 09",
      measurementsStatus: "missing",
      notes: "Corporate travel rushes",
    },
    {
      id: "C-1149",
      name: "Priya Shah",
      phone: "(555) 602-4489",
      email: "priya.shah@example.com",
      address: "240 E 49th St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Mar 16",
      measurementsStatus: "on_file",
      notes: "Prefers text updates",
      isVip: true,
    },
    {
      id: "C-1162",
      name: "Elena Morales",
      phone: "(555) 900-7714",
      email: "elena.morales@example.com",
      address: "9 Bayview Ct, Northport, NY",
      preferredLocationId: createLocationId("Long Island"),
      lastVisitLabel: "Mar 05",
      measurementsStatus: "needs_update",
      notes: "Mother-of-the-bride tailoring",
    },
    {
      id: "C-1177",
      name: "Marcus Reed",
      phone: "(555) 288-1130",
      email: "marcus.reed@example.com",
      address: "42-10 28th St, Long Island City, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 18",
      measurementsStatus: "missing",
      notes: "Performance wardrobe rushes",
    },
    {
      id: "C-1184",
      name: "Sofia Alvarez",
      phone: "(555) 410-6628",
      email: "sofia.alvarez@example.com",
      address: "80 E 73rd St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Feb 21",
      measurementsStatus: "on_file",
      notes: "Repeat black-tie client",
    },
  ];

  const customerEvents: DbCustomerEvent[] = [
    {
      id: "event-james-wedding",
      customerId: "C-1042",
      type: "wedding",
      title: "Spring wedding",
      eventDate: toDateString(withOffset(baseDate, 18)),
    },
    {
      id: "event-david-prom",
      customerId: "C-1116",
      type: "prom",
      title: "Prom night",
      eventDate: toDateString(withOffset(baseDate, 11)),
    },
    {
      id: "event-andrea-wedding",
      customerId: "C-1124",
      type: "wedding",
      title: "June wedding weekend",
      eventDate: toDateString(withOffset(baseDate, 24)),
    },
    {
      id: "event-priya-wedding",
      customerId: "C-1149",
      type: "wedding",
      title: "Destination wedding",
      eventDate: toDateString(withOffset(baseDate, 32)),
    },
    {
      id: "event-elena-wedding",
      customerId: "C-1162",
      type: "wedding",
      title: "Daughter's wedding",
      eventDate: toDateString(withOffset(baseDate, 19)),
    },
  ];

  const measurementSets: DbMeasurementSet[] = [
    {
      id: "SET-C1042-V4",
      customerId: "C-1042",
      label: "Version 4",
      takenAt: "Feb 28",
      note: "Latest on file",
      values: baseValues,
      suggested: true,
    },
    {
      id: "SET-C1042-V3",
      customerId: "C-1042",
      label: "Version 3",
      takenAt: "Jan 22",
      note: "Jan 22 • Tuxedo order",
      values: { ...baseValues, Chest: "40.25", Waist: "34.25", "Sleeve Length": "24.75" },
    },
    {
      id: "SET-C1042-V2",
      customerId: "C-1042",
      label: "Version 2",
      takenAt: "Sep 14",
      note: "Sep 14 • Alteration profile",
      values: { ...baseValues, Chest: "39.75", Waist: "33.75", "Back Length": "29.25" },
    },
    {
      id: "SET-C1116-V4",
      customerId: "C-1116",
      label: "Version 4",
      takenAt: "Mar 14",
      note: "Latest on file",
      values: davidValues,
      suggested: true,
    },
    {
      id: "SET-C1116-V3",
      customerId: "C-1116",
      label: "Version 3",
      takenAt: "Jan 08",
      note: "Rush suit baseline",
      values: { ...davidValues, Chest: "38.25", Waist: "31.75", Length: "40" },
    },
    {
      id: "SET-C1124-V2",
      customerId: "C-1124",
      label: "Version 2",
      takenAt: "Mar 12",
      note: "Latest on file",
      values: andreaValues,
      suggested: true,
    },
    {
      id: "SET-C1149-V5",
      customerId: "C-1149",
      label: "Version 5",
      takenAt: "Mar 16",
      note: "Latest on file",
      values: priyaValues,
      suggested: true,
    },
    {
      id: "SET-C1162-DRAFT",
      customerId: "C-1162",
      label: "Draft update",
      takenAt: "Mar 05",
      note: "Needs refresh before next fitting",
      values: { ...baseValues, Chest: "39.25", Waist: "34.5", Length: "40.75" },
      isDraft: true,
    },
    {
      id: "SET-C1184-V3",
      customerId: "C-1184",
      label: "Version 3",
      takenAt: "Feb 21",
      note: "Latest on file",
      values: sofiaValues,
      suggested: true,
    },
  ];

  const orders: DbOrder[] = [
    {
      id: "order-9001",
      displayId: "ORD-9001",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -3, 11, 20)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9002",
      displayId: "ORD-9002",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -2, 14, 5)),
      status: "partially_ready",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9003",
      displayId: "ORD-9003",
      payerCustomerId: "C-1116",
      payerName: "David Nguyen",
      orderType: "mixed",
      createdAt: toDateTimeString(withOffset(baseDate, -5, 9, 45)),
      status: "open",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-9004",
      displayId: "ORD-9004",
      payerCustomerId: null,
      payerName: "Walk-in customer",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 16, 10)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9005",
      displayId: "ORD-9005",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 10, 20)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9006",
      displayId: "ORD-9006",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, 0, 9, 10)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9007",
      displayId: "ORD-9007",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 12, 40)),
      status: "partially_ready",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9008",
      displayId: "ORD-9008",
      payerCustomerId: "C-1124",
      payerName: "Andrea Brooks",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -4, 13, 40)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9009",
      displayId: "ORD-9009",
      payerCustomerId: "C-1135",
      payerName: "Noah Bennett",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -2, 15, 20)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9010",
      displayId: "ORD-9010",
      payerCustomerId: "C-1149",
      payerName: "Priya Shah",
      orderType: "mixed",
      createdAt: toDateTimeString(withOffset(baseDate, -6, 10, 10)),
      status: "open",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-9011",
      displayId: "ORD-9011",
      payerCustomerId: "C-1162",
      payerName: "Elena Morales",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -3, 11, 45)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9012",
      displayId: "ORD-9012",
      payerCustomerId: "C-1177",
      payerName: "Marcus Reed",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 17, 5)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9013",
      displayId: "ORD-9013",
      payerCustomerId: "C-1184",
      payerName: "Sofia Alvarez",
      orderType: "custom",
      createdAt: "2026-02-21T12:20:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8821",
      displayId: "ORD-8821",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: "2026-02-28T10:00:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8610",
      displayId: "ORD-8610",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "alteration",
      createdAt: "2026-01-17T14:00:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8443",
      displayId: "ORD-8443",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: "2025-12-05T15:00:00",
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8904",
      displayId: "ORD-8904",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "mixed",
      createdAt: "2026-03-10T13:15:00",
      status: "open",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-8732",
      displayId: "ORD-8732",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: "2026-02-12T11:30:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8940",
      displayId: "ORD-8940",
      payerCustomerId: "C-1116",
      payerName: "David Nguyen",
      orderType: "alteration",
      createdAt: "2026-03-14T08:45:00",
      status: "partially_ready",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8528",
      displayId: "ORD-8528",
      payerCustomerId: "C-1116",
      payerName: "David Nguyen",
      orderType: "alteration",
      createdAt: "2026-01-08T09:00:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
  ];

  const orderScopes: DbOrderScope[] = [
    {
      id: "scope-9001-custom",
      orderId: "order-9001",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 1, 15, 0)),
      readyAt: null,
      eventId: "event-james-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9002-alteration",
      orderId: "order-9002",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 17, 30)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 13, 15)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9003-alteration",
      orderId: "order-9003",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, -1, 13, 0)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9003-custom",
      orderId: "order-9003",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 4, 12, 30)),
      readyAt: null,
      eventId: "event-david-prom",
      appointmentOptional: true,
    },
    {
      id: "scope-9004-alteration",
      orderId: "order-9004",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 2, 11, 0)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9005-alteration",
      orderId: "order-9005",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withMinuteDelta(liveReference, 45)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9006-custom",
      orderId: "order-9006",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withMinuteDelta(liveReference, 150)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9007-alteration",
      orderId: "order-9007",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 16, 0)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 11, 45)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9008-custom",
      orderId: "order-9008",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 6, 16, 0)),
      readyAt: null,
      eventId: "event-andrea-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9009-alteration",
      orderId: "order-9009",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 1, 15, 30)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9010-alteration",
      orderId: "order-9010",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 18, 0)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 11, 10)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9010-custom",
      orderId: "order-9010",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 3, 13, 0)),
      readyAt: null,
      eventId: "event-priya-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9011-custom",
      orderId: "order-9011",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 2, 14, 30)),
      readyAt: null,
      eventId: "event-elena-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9012-alteration",
      orderId: "order-9012",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 19, 15)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9013-custom",
      orderId: "order-9013",
      workflow: "custom",
      phase: "picked_up",
      promisedReadyAt: "2026-02-27T17:30:00",
      readyAt: "2026-02-26T15:15:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8821-custom",
      orderId: "order-8821",
      workflow: "custom",
      phase: "picked_up",
      promisedReadyAt: "2026-02-28T17:00:00",
      readyAt: "2026-02-28T14:30:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8610-alteration",
      orderId: "order-8610",
      workflow: "alteration",
      phase: "picked_up",
      promisedReadyAt: "2026-01-17T16:00:00",
      readyAt: "2026-01-17T12:00:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8443-custom",
      orderId: "order-8443",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: null,
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8904-alteration",
      orderId: "order-8904",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: "2026-03-10T17:00:00",
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8904-custom",
      orderId: "order-8904",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: "2026-03-15T16:00:00",
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8732-alteration",
      orderId: "order-8732",
      workflow: "alteration",
      phase: "picked_up",
      promisedReadyAt: "2026-02-12T17:00:00",
      readyAt: "2026-02-12T13:30:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8940-alteration",
      orderId: "order-8940",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: "2026-03-14T17:00:00",
      readyAt: "2026-03-14T12:00:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8528-alteration",
      orderId: "order-8528",
      workflow: "alteration",
      phase: "picked_up",
      promisedReadyAt: "2026-01-08T17:00:00",
      readyAt: "2026-01-08T12:00:00",
      eventId: null,
      appointmentOptional: true,
    },
  ];

  const orderScopeLines: DbOrderScopeLine[] = [
    { id: "line-9001-1", scopeId: "scope-9001-custom", label: "Two-piece suit", quantity: 1, unitPrice: 1495 },
    { id: "line-9002-1", scopeId: "scope-9002-alteration", label: "Dress hem", quantity: 1, unitPrice: 240 },
    { id: "line-9002-2", scopeId: "scope-9002-alteration", label: "Vest waist suppression", quantity: 1, unitPrice: 107.8 },
    { id: "line-9003-1", scopeId: "scope-9003-alteration", label: "Trouser taper", quantity: 1, unitPrice: 120 },
    { id: "line-9003-2", scopeId: "scope-9003-custom", label: "Dinner jacket", quantity: 1, unitPrice: 1495 },
    { id: "line-9003-3", scopeId: "scope-9003-custom", label: "Vest", quantity: 1, unitPrice: 741.85 },
    { id: "line-9004-1", scopeId: "scope-9004-alteration", label: "Pant hem", quantity: 1, unitPrice: 54.45 },
    { id: "line-9005-1", scopeId: "scope-9005-alteration", label: "Rush sleeve adjustment", quantity: 1, unitPrice: 95 },
    { id: "line-9006-1", scopeId: "scope-9006-custom", label: "Dinner jacket", quantity: 1, unitPrice: 1495 },
    { id: "line-9007-1", scopeId: "scope-9007-alteration", label: "Skirt hem", quantity: 1, unitPrice: 65 },
    { id: "line-9008-1", scopeId: "scope-9008-custom", label: "Wedding tuxedo", quantity: 1, unitPrice: 1895 },
    { id: "line-9009-1", scopeId: "scope-9009-alteration", label: "Jacket suppression", quantity: 1, unitPrice: 85 },
    { id: "line-9009-2", scopeId: "scope-9009-alteration", label: "Sleeve shorten", quantity: 1, unitPrice: 55 },
    { id: "line-9010-1", scopeId: "scope-9010-alteration", label: "Blouse sleeve taper", quantity: 1, unitPrice: 72 },
    { id: "line-9010-2", scopeId: "scope-9010-custom", label: "Reception jacket", quantity: 1, unitPrice: 1295 },
    { id: "line-9011-1", scopeId: "scope-9011-custom", label: "Mother-of-the-bride suit", quantity: 1, unitPrice: 1595 },
    { id: "line-9012-1", scopeId: "scope-9012-alteration", label: "Stage pant hem", quantity: 1, unitPrice: 45 },
    { id: "line-9012-2", scopeId: "scope-9012-alteration", label: "Jacket sleeve shorten", quantity: 1, unitPrice: 65 },
    { id: "line-9013-1", scopeId: "scope-9013-custom", label: "Black-tie tuxedo", quantity: 1, unitPrice: 1695 },
    { id: "line-8821-1", scopeId: "scope-8821-custom", label: "Custom navy suit", quantity: 1, unitPrice: 1495 },
    { id: "line-8610-1", scopeId: "scope-8610-alteration", label: "Trouser hem + taper", quantity: 1, unitPrice: 65 },
    { id: "line-8443-1", scopeId: "scope-8443-custom", label: "Dinner jacket consult", quantity: 1, unitPrice: 0 },
    { id: "line-8904-1", scopeId: "scope-8904-alteration", label: "Wedding party alteration set", quantity: 1, unitPrice: 320 },
    { id: "line-8904-2", scopeId: "scope-8904-custom", label: "Wedding jacket", quantity: 1, unitPrice: 0 },
    { id: "line-8732-1", scopeId: "scope-8732-alteration", label: "Bridesmaid dress fitting", quantity: 1, unitPrice: 95 },
    { id: "line-8940-1", scopeId: "scope-8940-alteration", label: "Rush suit sleeve adjustment", quantity: 1, unitPrice: 80 },
    { id: "line-8528-1", scopeId: "scope-8528-alteration", label: "Pant waist suppression", quantity: 1, unitPrice: 35 },
  ];

  const pickupNotifications: DbPickupNotification[] = [
    {
      id: "notify-9002-1",
      scopeId: "scope-9002-alteration",
      channel: "sms",
      status: "sent",
      sentAt: toDateTimeString(withOffset(baseDate, 0, 13, 30)),
      note: "Ready message sent; customer may pick up any time today.",
    },
    {
      id: "notify-9003-1",
      scopeId: "scope-9003-alteration",
      channel: "phone",
      status: "requested_pickup",
      sentAt: toDateTimeString(withOffset(baseDate, -1, 9, 0)),
      note: "Customer asked to be called once the custom scope is ready so both pieces can be collected together.",
    },
    {
      id: "notify-8940-1",
      scopeId: "scope-8940-alteration",
      channel: "sms",
      status: "acknowledged",
      sentAt: "2026-03-14T12:30:00",
      note: "Customer confirmed they will pick up after work.",
    },
    {
      id: "notify-9010-1",
      scopeId: "scope-9010-alteration",
      channel: "sms",
      status: "requested_pickup",
      sentAt: toDateTimeString(withOffset(baseDate, 0, 11, 20)),
      note: "Alteration scope is ready, but customer wants to collect once the custom jacket is complete.",
    },
    {
      id: "notify-9011-1",
      scopeId: "scope-9011-custom",
      channel: "email",
      status: "sent",
      sentAt: toDateTimeString(withOffset(baseDate, -1, 16, 45)),
      note: "Fabric approval sent with event deadline reminder.",
    },
  ];

  const pickupAppointments: DbPickupAppointment[] = [
    {
      id: "pickup-1003",
      orderId: "order-9003",
      scopeId: null,
      customerId: "C-1116",
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 14, 15)),
      locationId: createLocationId("Long Island"),
      status: "scheduled",
      summary: "Alterations: jeans, pants • Custom: shirt",
      issue: "Phone missing",
    },
    {
      id: "pickup-1006",
      orderId: "order-9002",
      scopeId: null,
      customerId: "C-1078",
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 16, 0)),
      locationId: createLocationId("Fifth Avenue"),
      status: "scheduled",
      summary: "Alterations: dress, vest • Custom: jacket",
      issue: "Bag and tag",
    },
    {
      id: "pickup-1009",
      orderId: "order-9004",
      scopeId: null,
      customerId: null,
      scheduledFor: toDateTimeString(withOffset(baseDate, 10, 13, 0)),
      locationId: createLocationId("Long Island"),
      status: "scheduled",
      summary: "Alterations: pants, shirt",
      issue: "Receipt match",
    },
    {
      id: "pickup-1010",
      orderId: "order-9010",
      scopeId: null,
      customerId: "C-1149",
      scheduledFor: toDateTimeString(withOffset(baseDate, 4, 17, 15)),
      locationId: createLocationId("Fifth Avenue"),
      status: "scheduled",
      summary: "Alterations: blouse sleeve taper • Custom: reception jacket",
      issue: "Garment bag prep",
    },
  ];

  const serviceAppointments: DbServiceAppointment[] = [
    {
      id: "APT-1001",
      customerId: "C-1078",
      customerName: "Maria Ellis",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 9, 30)),
      type: "Alteration fitting",
      status: "Ready to check in",
      issue: "Email missing",
    },
    {
      id: "APT-1002",
      customerId: "C-1042",
      customerName: "James Carter",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 11, 0)),
      type: "Custom suit consult",
      status: "Upcoming",
      issue: "Complete",
    },
    {
      id: "APT-1004",
      customerId: "C-1124",
      customerName: "Andrea Brooks",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 10, 0)),
      type: "First fitting",
      status: "Prep ticket",
      issue: "Measurements to review",
    },
    {
      id: "APT-1005",
      customerId: "C-1135",
      customerName: "Noah Bennett",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 13, 30)),
      type: "Custom jacket consult",
      status: "Upcoming",
      issue: "Fabric swatches",
    },
    {
      id: "APT-1007",
      customerId: "C-1116",
      customerName: "David Nguyen",
      workflow: "alteration",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 4, 12, 0)),
      type: "Trouser fitting",
      status: "Upcoming",
      issue: "Complete",
    },
    {
      id: "APT-1008",
      customerId: "C-1042",
      customerName: "James Carter",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 7, 15, 30)),
      type: "Jacket fitting",
      status: "Upcoming",
      issue: "Button confirmation",
    },
    {
      id: "APT-1009",
      customerId: "C-1149",
      customerName: "Priya Shah",
      workflow: "custom",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 2, 10, 30)),
      type: "Wedding jacket fitting",
      status: "Upcoming",
      issue: "Lapel decision",
    },
    {
      id: "APT-1010",
      customerId: "C-1162",
      customerName: "Elena Morales",
      workflow: "alteration",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 11, 15)),
      type: "Mother-of-the-bride fitting",
      status: "Prep ticket",
      issue: "Hem notes to confirm",
    },
    {
      id: "APT-1011",
      customerId: "C-1177",
      customerName: "Marcus Reed",
      workflow: "alteration",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 2, 14, 0)),
      type: "Performance fitting",
      status: "Upcoming",
      issue: "Rush turnaround",
    },
  ];

  const payments: DbPaymentRecord[] = [
    {
      id: "pay-9001",
      orderId: "order-9001",
      source: "square",
      status: "prepaid",
      amount: 747.5,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 10, 0)),
      squarePaymentId: "sq_pay_9001",
    },
    {
      id: "pay-9002",
      orderId: "order-9002",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9003",
      orderId: "order-9003",
      source: "square",
      status: "prepaid",
      amount: 1080,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 11, 30)),
      squarePaymentId: "sq_pay_9003",
    },
    {
      id: "pay-9004",
      orderId: "order-9004",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9005",
      orderId: "order-9005",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9006",
      orderId: "order-9006",
      source: "square",
      status: "prepaid",
      amount: 747.5,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 10, 30)),
      squarePaymentId: "sq_pay_9006",
    },
    {
      id: "pay-9007",
      orderId: "order-9007",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9008",
      orderId: "order-9008",
      source: "square",
      status: "prepaid",
      amount: 950,
      collectedAt: toDateTimeString(withOffset(baseDate, -4, 14, 0)),
      squarePaymentId: "sq_pay_9008",
    },
    {
      id: "pay-9009",
      orderId: "order-9009",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9010",
      orderId: "order-9010",
      source: "square",
      status: "prepaid",
      amount: 600,
      collectedAt: toDateTimeString(withOffset(baseDate, -6, 10, 45)),
      squarePaymentId: "sq_pay_9010",
    },
    {
      id: "pay-9011",
      orderId: "order-9011",
      source: "square",
      status: "prepaid",
      amount: 800,
      collectedAt: toDateTimeString(withOffset(baseDate, -3, 12, 0)),
      squarePaymentId: "sq_pay_9011",
    },
    {
      id: "pay-9012",
      orderId: "order-9012",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9013",
      orderId: "order-9013",
      source: "square",
      status: "prepaid",
      amount: 1695,
      collectedAt: "2026-02-26T15:00:00",
      squarePaymentId: "sq_pay_9013",
    },
    {
      id: "pay-8821",
      orderId: "order-8821",
      source: "square",
      status: "prepaid",
      amount: 1495,
      collectedAt: "2026-02-28T14:00:00",
      squarePaymentId: "sq_pay_8821",
    },
    {
      id: "pay-8610",
      orderId: "order-8610",
      source: "square",
      status: "prepaid",
      amount: 65,
      collectedAt: "2026-01-17T12:00:00",
      squarePaymentId: "sq_pay_8610",
    },
    {
      id: "pay-8443",
      orderId: "order-8443",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8904",
      orderId: "order-8904",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8732",
      orderId: "order-8732",
      source: "square",
      status: "prepaid",
      amount: 95,
      collectedAt: "2026-02-12T13:30:00",
      squarePaymentId: "sq_pay_8732",
    },
    {
      id: "pay-8940",
      orderId: "order-8940",
      source: "prototype",
      status: "pay_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8528",
      orderId: "order-8528",
      source: "square",
      status: "prepaid",
      amount: 35,
      collectedAt: "2026-01-08T12:00:00",
      squarePaymentId: "sq_pay_8528",
    },
  ];

  const squareLinks: DbSquareLink[] = orders.map((order) => ({
    orderId: order.id,
    squareOrderId: `sq_order_${order.displayId.toLowerCase()}`,
  }));

  const airtableLinks: DbAirtableLink[] = orders.map((order) => ({
    orderId: order.id,
    airtableRecordId: `rec_${order.displayId.toLowerCase()}`,
  }));

  return {
    generatedAt: toDateTimeString(baseDate),
    locations,
    customers,
    customerEvents,
    measurementSets,
    orders,
    orderScopes,
    orderScopeLines,
    pickupNotifications,
    pickupAppointments,
    serviceAppointments,
    payments,
    squareLinks,
    airtableLinks,
  };
}
