import type {
  DbCustomer,
  DbCustomerEvent,
  DbLocation,
  DbMeasurementSet,
} from "../schema";
import {
  andreaValues,
  baseValues,
  createLocationId,
  davidValues,
  priyaValues,
  RuntimeSeedDates,
  sofiaValues,
  toDateString,
  withOffset,
} from "./support";

const additionalCustomers: DbCustomer[] = [
  {
    id: "C-1191",
    name: "Olivia Chen",
    phone: "(555) 318-4420",
    email: "olivia.chen@example.com",
    address: "19 E 65th St, New York, NY",
    preferredLocationId: createLocationId("Fifth Avenue"),
    lastVisitLabel: "Mar 19",
    measurementsStatus: "on_file",
    marketingOptIn: true,
    notes: "Prefers clean minimal styling",
  },
  {
    id: "C-1203",
    name: "Ethan Ross",
    phone: "(555) 622-9104",
    email: "ethan.ross@example.com",
    address: "76 Main St, Huntington, NY",
    preferredLocationId: createLocationId("Long Island"),
    lastVisitLabel: "Mar 08",
    measurementsStatus: "missing",
    marketingOptIn: true,
    notes: "Prom timeline; asked for bolder lapel options",
  },
  {
    id: "C-1214",
    name: "Lily Park",
    phone: "(555) 447-2201",
    email: "lily.park@example.com",
    address: "36-11 Broadway, Astoria, NY",
    preferredLocationId: createLocationId("Queens"),
    lastVisitLabel: "Mar 18",
    measurementsStatus: "missing",
    marketingOptIn: true,
    notes: "Bridesmaid alterations and possible dinner jacket consult",
  },
  {
    id: "C-1226",
    name: "Gabriel Stone",
    phone: "(555) 205-8824",
    email: "gabriel.stone@example.com",
    address: "205 E 78th St, New York, NY",
    preferredLocationId: createLocationId("Fifth Avenue"),
    lastVisitLabel: "Mar 13",
    measurementsStatus: "on_file",
    marketingOptIn: true,
    notes: "Frequently combines tailoring with same-week pickups",
    isVip: true,
  },
  {
    id: "C-1238",
    name: "Zoe Kim",
    phone: "(555) 701-2268",
    email: "",
    address: "45-09 Center Blvd, Long Island City, NY",
    preferredLocationId: createLocationId("Queens"),
    lastVisitLabel: "Feb 25",
    measurementsStatus: "missing",
    marketingOptIn: true,
    notes: "Editorial styling pull; email never captured",
  },
  {
    id: "C-1247",
    name: "Malik Johnson",
    phone: "(555) 880-6619",
    email: "malik.johnson@example.com",
    address: "52 W 57th St, New York, NY",
    preferredLocationId: createLocationId("Fifth Avenue"),
    lastVisitLabel: "Mar 11",
    measurementsStatus: "on_file",
    marketingOptIn: true,
    notes: "Wedding capsule in progress",
  },
  {
    id: "C-1259",
    name: "Harper Cole",
    phone: "(555) 332-0048",
    email: "harper.cole@example.com",
    address: "180 Main St, Huntington, NY",
    preferredLocationId: createLocationId("Long Island"),
    lastVisitLabel: "Mar 06",
    measurementsStatus: "missing",
    marketingOptIn: false,
    notes: "Formalwear refresh; usually books late-day fittings",
  },
  {
    id: "C-1271",
    name: "Victor Ramirez",
    phone: "(555) 422-1173",
    email: "victor.ramirez@example.com",
    address: "29-03 30th Dr, Astoria, NY",
    preferredLocationId: createLocationId("Queens"),
    lastVisitLabel: "Feb 17",
    measurementsStatus: "on_file",
    marketingOptIn: true,
    notes: "Repeat suit client with theater schedule constraints",
  },
  {
    id: "C-1282",
    name: "Ava Patel",
    phone: "(555) 913-6418",
    email: "ava.patel@example.com",
    address: "320 E 56th St, New York, NY",
    preferredLocationId: createLocationId("Fifth Avenue"),
    lastVisitLabel: "Mar 20",
    measurementsStatus: "missing",
    marketingOptIn: false,
    notes: "Shirt alterations; very schedule-sensitive",
  },
  {
    id: "C-1296",
    name: "Owen Sullivan",
    phone: "(555) 600-8812",
    email: "owen.sullivan@example.com",
    address: "12 Wall St, Huntington, NY",
    preferredLocationId: createLocationId("Long Island"),
    lastVisitLabel: "Feb 10",
    measurementsStatus: "on_file",
    marketingOptIn: true,
    notes: "Classic office suiting; usually picks up on Fridays",
  },
  {
    id: "C-1304",
    name: "Chloe Friedman",
    phone: "(555) 111-2480",
    email: "chloe.friedman@example.com",
    address: "",
    preferredLocationId: createLocationId("Fifth Avenue"),
    lastVisitLabel: "Mar 07",
    measurementsStatus: "missing",
    marketingOptIn: true,
    notes: "Address missing; stylist referral",
  },
  {
    id: "C-1317",
    name: "Benjamin Lee",
    phone: "(555) 520-3314",
    email: "benjamin.lee@example.com",
    address: "38-12 31st Ave, Astoria, NY",
    preferredLocationId: createLocationId("Queens"),
    lastVisitLabel: "Mar 03",
    measurementsStatus: "on_file",
    marketingOptIn: true,
    notes: "Dinner suit build for spring gala",
  },
  {
    id: "C-1325",
    name: "Tessa Monroe",
    phone: "(555) 748-5502",
    email: "tessa.monroe@example.com",
    address: "88 W 72nd St, New York, NY",
    preferredLocationId: createLocationId("Fifth Avenue"),
    lastVisitLabel: "Mar 15",
    measurementsStatus: "missing",
    marketingOptIn: true,
    notes: "Editorial tailoring with frequent note changes",
  },
];

const additionalMeasurementSets: DbMeasurementSet[] = [
  {
    id: "SET-C1191-V2",
    customerId: "C-1191",
    label: "Version 2",
    takenAt: "Mar 19",
    note: "Latest on file",
    values: { ...baseValues, Chest: "35.75", Waist: "28.5", Length: "39.75" },
    suggested: true,
  },
  {
    id: "SET-C1203-V1",
    customerId: "C-1203",
    label: "Version 1",
    takenAt: "Jan 28",
    note: "Needs refresh before prom fitting",
    values: { ...davidValues, Chest: "39", Waist: "32.25", Length: "40.5" },
    suggested: true,
  },
  {
    id: "SET-C1226-V3",
    customerId: "C-1226",
    label: "Version 3",
    takenAt: "Mar 13",
    note: "Latest on file",
    values: { ...baseValues, Chest: "41.25", Waist: "35", Length: "41.5" },
    suggested: true,
  },
  {
    id: "SET-C1247-V2",
    customerId: "C-1247",
    label: "Version 2",
    takenAt: "Mar 11",
    note: "Latest on file",
    values: { ...baseValues, Chest: "42", Waist: "36", Length: "41.75" },
    suggested: true,
  },
  {
    id: "SET-C1259-V1",
    customerId: "C-1259",
    label: "Version 1",
    takenAt: "Mar 06",
    note: "Latest on file",
    values: { ...andreaValues, Chest: "35.75", Waist: "29.25", Length: "40.25" },
    suggested: true,
  },
  {
    id: "SET-C1271-V1",
    customerId: "C-1271",
    label: "Version 1",
    takenAt: "Feb 17",
    note: "Latest on file",
    values: { ...davidValues, Chest: "39.75", Waist: "33", Length: "40.75" },
    suggested: true,
  },
  {
    id: "SET-C1296-V4",
    customerId: "C-1296",
    label: "Version 4",
    takenAt: "Feb 10",
    note: "Latest on file",
    values: { ...baseValues, Chest: "40.25", Waist: "34.25", Length: "41" },
    suggested: true,
  },
  {
    id: "SET-C1317-V2",
    customerId: "C-1317",
    label: "Version 2",
    takenAt: "Mar 03",
    note: "Latest on file",
    values: { ...baseValues, Chest: "38.75", Waist: "32.5", Length: "40.5" },
    suggested: true,
  },
  {
    id: "SET-C1325-V2",
    customerId: "C-1325",
    label: "Version 2",
    takenAt: "Feb 06",
    note: "Needs update before editorial fitting",
    values: { ...sofiaValues, Chest: "36.25", Waist: "29.25", Length: "40.75" },
    suggested: true,
  },
];

export function createLocations(): DbLocation[] {
  return [
    { id: createLocationId("Fifth Avenue"), name: "Fifth Avenue" },
    { id: createLocationId("Queens"), name: "Queens" },
    { id: createLocationId("Long Island"), name: "Long Island" },
  ];
}

export function createCustomers(): DbCustomer[] {
  return [
    {
      id: "C-1042",
      name: "James Carter",
      phone: "(555) 201-9044",
      email: "james.carter@example.com",
      address: "14 E 61st St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Feb 28",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Prefers slim fit",
      isVip: true,
    },
    {
      id: "C-1078",
      name: "Maria Ellis",
      phone: "(555) 884-7712",
      email: "",
      address: "22-18 33rd Ave, Astoria, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 10",
      measurementsStatus: "missing",
      marketingOptIn: true,
      notes: "Wedding party order",
    },
    {
      id: "C-1116",
      name: "David Nguyen",
      phone: "(555) 490-1162",
      email: "d.nguyen@example.com",
      address: "48 Harbor Ln, Huntington, NY",
      preferredLocationId: createLocationId("Long Island"),
      lastVisitLabel: "Mar 14",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Rush alterations",
    },
    {
      id: "C-1124",
      name: "Andrea Brooks",
      phone: "",
      email: "andrea.brooks@example.com",
      address: "117 W 58th St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Mar 12",
      measurementsStatus: "missing",
      marketingOptIn: true,
      notes: "Bridal party tailoring",
    },
    {
      id: "C-1135",
      name: "Noah Bennett",
      phone: "(555) 771-0031",
      email: "noah.bennett@example.com",
      address: "31-22 Crescent St, Astoria, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 09",
      measurementsStatus: "missing",
      marketingOptIn: false,
      notes: "Corporate travel rushes",
    },
    {
      id: "C-1149",
      name: "Priya Shah",
      phone: "(555) 602-4489",
      email: "priya.shah@example.com",
      address: "240 E 49th St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Mar 16",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Prefers text updates",
      isVip: true,
    },
    {
      id: "C-1162",
      name: "Elena Morales",
      phone: "(555) 900-7714",
      email: "elena.morales@example.com",
      address: "",
      preferredLocationId: createLocationId("Long Island"),
      lastVisitLabel: "Mar 05",
      measurementsStatus: "missing",
      marketingOptIn: true,
      notes: "Mother-of-the-bride tailoring",
    },
    {
      id: "C-1177",
      name: "Marcus Reed",
      phone: "(555) 288-1130",
      email: "marcus.reed@example.com",
      address: "42-10 28th St, Long Island City, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 18",
      measurementsStatus: "missing",
      marketingOptIn: true,
      notes: "Performance wardrobe rushes",
    },
    {
      id: "C-1184",
      name: "Sofia Alvarez",
      phone: "(555) 410-6628",
      email: "sofia.alvarez@example.com",
      address: "80 E 73rd St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Feb 21",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Repeat black-tie client",
    },
    ...additionalCustomers,
  ];
}

export function createCustomerEvents({ baseDate }: RuntimeSeedDates): DbCustomerEvent[] {
  return [
    {
      id: "event-james-wedding",
      customerId: "C-1042",
      type: "wedding",
      title: "Spring wedding",
      eventDate: toDateString(withOffset(baseDate, 18)),
    },
    {
      id: "event-david-prom",
      customerId: "C-1116",
      type: "prom",
      title: "Prom night",
      eventDate: toDateString(withOffset(baseDate, 11)),
    },
    {
      id: "event-andrea-wedding",
      customerId: "C-1124",
      type: "wedding",
      title: "June wedding weekend",
      eventDate: toDateString(withOffset(baseDate, 24)),
    },
    {
      id: "event-priya-wedding",
      customerId: "C-1149",
      type: "wedding",
      title: "Destination wedding",
      eventDate: toDateString(withOffset(baseDate, 32)),
    },
    {
      id: "event-elena-wedding",
      customerId: "C-1162",
      type: "wedding",
      title: "Daughter's wedding",
      eventDate: toDateString(withOffset(baseDate, 19)),
    },
    {
      id: "event-ethan-prom",
      customerId: "C-1203",
      type: "prom",
      title: "Senior prom",
      eventDate: toDateString(withOffset(baseDate, 15)),
    },
    {
      id: "event-gabriel-wedding",
      customerId: "C-1226",
      type: "wedding",
      title: "Late spring ceremony",
      eventDate: toDateString(withOffset(baseDate, 41)),
    },
    {
      id: "event-malik-wedding",
      customerId: "C-1247",
      type: "wedding",
      title: "Ceremony weekend",
      eventDate: toDateString(withOffset(baseDate, 22)),
    },
    {
      id: "event-benjamin-gala",
      customerId: "C-1317",
      type: "none",
      title: "Spring gala",
      eventDate: toDateString(withOffset(baseDate, 12)),
    },
  ];
}

export function createMeasurementSets(): DbMeasurementSet[] {
  return [
    {
      id: "SET-C1078-V1",
      customerId: "C-1078",
      label: "Version 1",
      takenAt: "Mar 10",
      note: "Wedding party baseline",
      values: { ...andreaValues, Chest: "35.5", Waist: "29.25", "Sleeve Length": "23.75" },
      suggested: true,
    },
    {
      id: "SET-C1042-V4",
      customerId: "C-1042",
      label: "Version 4",
      takenAt: "Feb 28",
      note: "Latest on file",
      values: baseValues,
      suggested: true,
    },
    {
      id: "SET-C1042-V3",
      customerId: "C-1042",
      label: "Version 3",
      takenAt: "Jan 22",
      note: "Jan 22 • Tuxedo order",
      values: { ...baseValues, Chest: "40.25", Waist: "34.25", "Sleeve Length": "24.75" },
    },
    {
      id: "SET-C1042-V2",
      customerId: "C-1042",
      label: "Version 2",
      takenAt: "Sep 14",
      note: "Sep 14 • Alteration profile",
      values: { ...baseValues, Chest: "39.75", Waist: "33.75", "Back Length": "29.25" },
    },
    {
      id: "SET-C1116-V4",
      customerId: "C-1116",
      label: "Version 4",
      takenAt: "Mar 14",
      note: "Latest on file",
      values: davidValues,
      suggested: true,
    },
    {
      id: "SET-C1116-V3",
      customerId: "C-1116",
      label: "Version 3",
      takenAt: "Jan 08",
      note: "Rush suit baseline",
      values: { ...davidValues, Chest: "38.25", Waist: "31.75", Length: "40" },
    },
    {
      id: "SET-C1124-V2",
      customerId: "C-1124",
      label: "Version 2",
      takenAt: "Mar 12",
      note: "Latest on file",
      values: andreaValues,
      suggested: true,
    },
    {
      id: "SET-C1149-V5",
      customerId: "C-1149",
      label: "Version 5",
      takenAt: "Mar 16",
      note: "Latest on file",
      values: priyaValues,
      suggested: true,
    },
    {
      id: "SET-C1162-V1",
      customerId: "C-1162",
      label: "Version 1",
      takenAt: "Mar 05",
      note: "Latest on file",
      values: { ...baseValues, Chest: "39.25", Waist: "34.5", Length: "40.75" },
      suggested: true,
    },
    {
      id: "SET-C1184-V3",
      customerId: "C-1184",
      label: "Version 3",
      takenAt: "Feb 21",
      note: "Latest on file",
      values: sofiaValues,
      suggested: true,
    },
    {
      id: "SET-C1214-V1",
      customerId: "C-1214",
      label: "Version 1",
      takenAt: "Mar 18",
      note: "Bridesmaid jacket consult",
      values: { ...andreaValues, Chest: "34.75", Waist: "28.75", Length: "39.5" },
      suggested: true,
    },
    {
      id: "SET-C1238-V1",
      customerId: "C-1238",
      label: "Version 1",
      takenAt: "Feb 25",
      note: "Editorial tuxedo baseline",
      values: { ...sofiaValues, Chest: "35.25", Waist: "28.5", Length: "40.25" },
      suggested: true,
    },
    ...additionalMeasurementSets,
  ];
}
