import type {
  DbCustomer,
  DbCustomerEvent,
  DbLocation,
  DbMeasurementSet,
} from "../schema";
import {
  andreaValues,
  baseValues,
  createLocationId,
  davidValues,
  priyaValues,
  RuntimeSeedDates,
  sofiaValues,
  toDateString,
  withOffset,
} from "./support";

export function createLocations(): DbLocation[] {
  return [
    { id: createLocationId("Fifth Avenue"), name: "Fifth Avenue" },
    { id: createLocationId("Queens"), name: "Queens" },
    { id: createLocationId("Long Island"), name: "Long Island" },
  ];
}

export function createCustomers(): DbCustomer[] {
  return [
    {
      id: "C-1042",
      name: "James Carter",
      phone: "(555) 201-9044",
      email: "james.carter@example.com",
      address: "14 E 61st St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Feb 28",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Prefers slim fit",
      isVip: true,
    },
    {
      id: "C-1078",
      name: "Maria Ellis",
      phone: "(555) 884-7712",
      email: "",
      address: "22-18 33rd Ave, Astoria, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 10",
      measurementsStatus: "missing",
      marketingOptIn: true,
      notes: "Wedding party order",
    },
    {
      id: "C-1116",
      name: "David Nguyen",
      phone: "(555) 490-1162",
      email: "d.nguyen@example.com",
      address: "48 Harbor Ln, Huntington, NY",
      preferredLocationId: createLocationId("Long Island"),
      lastVisitLabel: "Mar 14",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Rush alterations",
    },
    {
      id: "C-1124",
      name: "Andrea Brooks",
      phone: "",
      email: "andrea.brooks@example.com",
      address: "117 W 58th St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Mar 12",
      measurementsStatus: "needs_update",
      marketingOptIn: true,
      notes: "Bridal party tailoring",
    },
    {
      id: "C-1135",
      name: "Noah Bennett",
      phone: "(555) 771-0031",
      email: "noah.bennett@example.com",
      address: "31-22 Crescent St, Astoria, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 09",
      measurementsStatus: "missing",
      marketingOptIn: false,
      notes: "Corporate travel rushes",
    },
    {
      id: "C-1149",
      name: "Priya Shah",
      phone: "(555) 602-4489",
      email: "priya.shah@example.com",
      address: "240 E 49th St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Mar 16",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Prefers text updates",
      isVip: true,
    },
    {
      id: "C-1162",
      name: "Elena Morales",
      phone: "(555) 900-7714",
      email: "elena.morales@example.com",
      address: "",
      preferredLocationId: createLocationId("Long Island"),
      lastVisitLabel: "Mar 05",
      measurementsStatus: "needs_update",
      marketingOptIn: true,
      notes: "Mother-of-the-bride tailoring",
    },
    {
      id: "C-1177",
      name: "Marcus Reed",
      phone: "(555) 288-1130",
      email: "marcus.reed@example.com",
      address: "42-10 28th St, Long Island City, NY",
      preferredLocationId: createLocationId("Queens"),
      lastVisitLabel: "Mar 18",
      measurementsStatus: "missing",
      marketingOptIn: true,
      notes: "Performance wardrobe rushes",
    },
    {
      id: "C-1184",
      name: "Sofia Alvarez",
      phone: "(555) 410-6628",
      email: "sofia.alvarez@example.com",
      address: "80 E 73rd St, New York, NY",
      preferredLocationId: createLocationId("Fifth Avenue"),
      lastVisitLabel: "Feb 21",
      measurementsStatus: "on_file",
      marketingOptIn: true,
      notes: "Repeat black-tie client",
    },
  ];
}

export function createCustomerEvents({ baseDate }: RuntimeSeedDates): DbCustomerEvent[] {
  return [
    {
      id: "event-james-wedding",
      customerId: "C-1042",
      type: "wedding",
      title: "Spring wedding",
      eventDate: toDateString(withOffset(baseDate, 18)),
    },
    {
      id: "event-david-prom",
      customerId: "C-1116",
      type: "prom",
      title: "Prom night",
      eventDate: toDateString(withOffset(baseDate, 11)),
    },
    {
      id: "event-andrea-wedding",
      customerId: "C-1124",
      type: "wedding",
      title: "June wedding weekend",
      eventDate: toDateString(withOffset(baseDate, 24)),
    },
    {
      id: "event-priya-wedding",
      customerId: "C-1149",
      type: "wedding",
      title: "Destination wedding",
      eventDate: toDateString(withOffset(baseDate, 32)),
    },
    {
      id: "event-elena-wedding",
      customerId: "C-1162",
      type: "wedding",
      title: "Daughter's wedding",
      eventDate: toDateString(withOffset(baseDate, 19)),
    },
  ];
}

export function createMeasurementSets(): DbMeasurementSet[] {
  return [
    {
      id: "SET-C1042-V4",
      customerId: "C-1042",
      label: "Version 4",
      takenAt: "Feb 28",
      note: "Latest on file",
      values: baseValues,
      suggested: true,
    },
    {
      id: "SET-C1042-V3",
      customerId: "C-1042",
      label: "Version 3",
      takenAt: "Jan 22",
      note: "Jan 22 • Tuxedo order",
      values: { ...baseValues, Chest: "40.25", Waist: "34.25", "Sleeve Length": "24.75" },
    },
    {
      id: "SET-C1042-V2",
      customerId: "C-1042",
      label: "Version 2",
      takenAt: "Sep 14",
      note: "Sep 14 • Alteration profile",
      values: { ...baseValues, Chest: "39.75", Waist: "33.75", "Back Length": "29.25" },
    },
    {
      id: "SET-C1116-V4",
      customerId: "C-1116",
      label: "Version 4",
      takenAt: "Mar 14",
      note: "Latest on file",
      values: davidValues,
      suggested: true,
    },
    {
      id: "SET-C1116-V3",
      customerId: "C-1116",
      label: "Version 3",
      takenAt: "Jan 08",
      note: "Rush suit baseline",
      values: { ...davidValues, Chest: "38.25", Waist: "31.75", Length: "40" },
    },
    {
      id: "SET-C1124-V2",
      customerId: "C-1124",
      label: "Version 2",
      takenAt: "Mar 12",
      note: "Latest on file",
      values: andreaValues,
      suggested: true,
    },
    {
      id: "SET-C1149-V5",
      customerId: "C-1149",
      label: "Version 5",
      takenAt: "Mar 16",
      note: "Latest on file",
      values: priyaValues,
      suggested: true,
    },
    {
      id: "SET-C1162-DRAFT",
      customerId: "C-1162",
      label: "Draft update",
      takenAt: "Mar 05",
      note: "Needs refresh before next fitting",
      values: { ...baseValues, Chest: "39.25", Waist: "34.5", Length: "40.75" },
      isDraft: true,
    },
    {
      id: "SET-C1184-V3",
      customerId: "C-1184",
      label: "Version 3",
      takenAt: "Feb 21",
      note: "Latest on file",
      values: sofiaValues,
      suggested: true,
    },
  ];
}
