import type {
  DbOrder,
  DbOrderScope,
  DbOrderScopeLine,
  DbPaymentRecord,
  DbSquareLink,
} from "../schema";
import {
  RuntimeSeedDates,
  toDateTimeString,
  withMinuteDelta,
  withOffset,
} from "./support";

export function createOrders({ baseDate }: RuntimeSeedDates): DbOrder[] {
  return [
    {
      id: "order-9001",
      displayId: "ORD-9001",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -3, 11, 20)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9002",
      displayId: "ORD-9002",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -2, 14, 5)),
      status: "partially_ready",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9003",
      displayId: "ORD-9003",
      payerCustomerId: "C-1116",
      payerName: "David Nguyen",
      orderType: "mixed",
      createdAt: toDateTimeString(withOffset(baseDate, -5, 9, 45)),
      status: "open",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-9004",
      displayId: "ORD-9004",
      payerCustomerId: null,
      payerName: "Walk-in customer",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 16, 10)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9005",
      displayId: "ORD-9005",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 10, 20)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9006",
      displayId: "ORD-9006",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, 0, 9, 10)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9007",
      displayId: "ORD-9007",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 12, 40)),
      status: "partially_ready",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9008",
      displayId: "ORD-9008",
      payerCustomerId: "C-1124",
      payerName: "Andrea Brooks",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -4, 13, 40)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9009",
      displayId: "ORD-9009",
      payerCustomerId: "C-1135",
      payerName: "Noah Bennett",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -2, 15, 20)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9010",
      displayId: "ORD-9010",
      payerCustomerId: "C-1149",
      payerName: "Priya Shah",
      orderType: "mixed",
      createdAt: toDateTimeString(withOffset(baseDate, -6, 10, 10)),
      status: "open",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-9011",
      displayId: "ORD-9011",
      payerCustomerId: "C-1162",
      payerName: "Elena Morales",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -3, 11, 45)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9012",
      displayId: "ORD-9012",
      payerCustomerId: "C-1177",
      payerName: "Marcus Reed",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 17, 5)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9013",
      displayId: "ORD-9013",
      payerCustomerId: "C-1184",
      payerName: "Sofia Alvarez",
      orderType: "custom",
      createdAt: "2026-02-21T12:20:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8821",
      displayId: "ORD-8821",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: "2026-02-28T10:00:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8610",
      displayId: "ORD-8610",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "alteration",
      createdAt: "2026-01-17T14:00:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8443",
      displayId: "ORD-8443",
      payerCustomerId: "C-1042",
      payerName: "James Carter",
      orderType: "custom",
      createdAt: "2025-12-05T15:00:00",
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8904",
      displayId: "ORD-8904",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "mixed",
      createdAt: "2026-03-10T13:15:00",
      status: "open",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-8732",
      displayId: "ORD-8732",
      payerCustomerId: "C-1078",
      payerName: "Maria Ellis",
      orderType: "alteration",
      createdAt: "2026-02-12T11:30:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8940",
      displayId: "ORD-8940",
      payerCustomerId: "C-1116",
      payerName: "David Nguyen",
      orderType: "alteration",
      createdAt: "2026-03-14T08:45:00",
      status: "partially_ready",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-8528",
      displayId: "ORD-8528",
      payerCustomerId: "C-1116",
      payerName: "David Nguyen",
      orderType: "alteration",
      createdAt: "2026-01-08T09:00:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9014",
      displayId: "ORD-9014",
      payerCustomerId: "C-1191",
      payerName: "Olivia Chen",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -2, 11, 15)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9015",
      displayId: "ORD-9015",
      payerCustomerId: "C-1203",
      payerName: "Ethan Ross",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -3, 15, 10)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9016",
      displayId: "ORD-9016",
      payerCustomerId: "C-1214",
      payerName: "Lily Park",
      orderType: "mixed",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 13, 5)),
      status: "partially_ready",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-9017",
      displayId: "ORD-9017",
      payerCustomerId: "C-1226",
      payerName: "Gabriel Stone",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -4, 10, 25)),
      status: "partially_ready",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9018",
      displayId: "ORD-9018",
      payerCustomerId: "C-1238",
      payerName: "Zoe Kim",
      orderType: "custom",
      createdAt: "2026-02-19T12:45:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9019",
      displayId: "ORD-9019",
      payerCustomerId: "C-1247",
      payerName: "Malik Johnson",
      orderType: "mixed",
      createdAt: toDateTimeString(withOffset(baseDate, -2, 16, 20)),
      status: "open",
      holdUntilAllScopesReady: true,
    },
    {
      id: "order-9020",
      displayId: "ORD-9020",
      payerCustomerId: "C-1259",
      payerName: "Harper Cole",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, -1, 9, 35)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9021",
      displayId: "ORD-9021",
      payerCustomerId: "C-1296",
      payerName: "Owen Sullivan",
      orderType: "custom",
      createdAt: "2026-02-11T11:10:00",
      status: "complete",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9022",
      displayId: "ORD-9022",
      payerCustomerId: "C-1282",
      payerName: "Ava Patel",
      orderType: "alteration",
      createdAt: toDateTimeString(withOffset(baseDate, 0, 10, 50)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
    {
      id: "order-9023",
      displayId: "ORD-9023",
      payerCustomerId: "C-1317",
      payerName: "Benjamin Lee",
      orderType: "custom",
      createdAt: toDateTimeString(withOffset(baseDate, -5, 14, 10)),
      status: "open",
      holdUntilAllScopesReady: false,
    },
  ];
}

export function createOrderScopes({ baseDate, liveReference }: RuntimeSeedDates): DbOrderScope[] {
  return [
    {
      id: "scope-9001-custom",
      orderId: "order-9001",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 1, 15, 0)),
      readyAt: null,
      eventId: "event-james-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9002-alteration",
      orderId: "order-9002",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 17, 30)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 13, 15)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9003-alteration",
      orderId: "order-9003",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, -1, 13, 0)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9003-custom",
      orderId: "order-9003",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 4, 12, 30)),
      readyAt: null,
      eventId: "event-david-prom",
      appointmentOptional: true,
    },
    {
      id: "scope-9004-alteration",
      orderId: "order-9004",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 2, 11, 0)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9005-alteration",
      orderId: "order-9005",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withMinuteDelta(liveReference, 45)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9006-custom",
      orderId: "order-9006",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withMinuteDelta(liveReference, 150)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9007-alteration",
      orderId: "order-9007",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 16, 0)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 11, 45)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9008-custom",
      orderId: "order-9008",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 6, 16, 0)),
      readyAt: null,
      eventId: "event-andrea-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9009-alteration",
      orderId: "order-9009",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 1, 15, 30)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9010-alteration",
      orderId: "order-9010",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 18, 0)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 11, 10)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9010-custom",
      orderId: "order-9010",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 3, 13, 0)),
      readyAt: null,
      eventId: "event-priya-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9011-custom",
      orderId: "order-9011",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 2, 14, 30)),
      readyAt: null,
      eventId: "event-elena-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9012-alteration",
      orderId: "order-9012",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 19, 15)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9013-custom",
      orderId: "order-9013",
      workflow: "custom",
      phase: "picked_up",
      promisedReadyAt: "2026-02-27T17:30:00",
      readyAt: "2026-02-26T15:15:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8821-custom",
      orderId: "order-8821",
      workflow: "custom",
      phase: "picked_up",
      promisedReadyAt: "2026-02-28T17:00:00",
      readyAt: "2026-02-28T14:30:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8610-alteration",
      orderId: "order-8610",
      workflow: "alteration",
      phase: "picked_up",
      promisedReadyAt: "2026-01-17T16:00:00",
      readyAt: "2026-01-17T12:00:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8443-custom",
      orderId: "order-8443",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: null,
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8904-alteration",
      orderId: "order-8904",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: "2026-03-10T17:00:00",
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8904-custom",
      orderId: "order-8904",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: "2026-03-15T16:00:00",
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8732-alteration",
      orderId: "order-8732",
      workflow: "alteration",
      phase: "picked_up",
      promisedReadyAt: "2026-02-12T17:00:00",
      readyAt: "2026-02-12T13:30:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8940-alteration",
      orderId: "order-8940",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: "2026-03-14T17:00:00",
      readyAt: "2026-03-14T12:00:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-8528-alteration",
      orderId: "order-8528",
      workflow: "alteration",
      phase: "picked_up",
      promisedReadyAt: "2026-01-08T17:00:00",
      readyAt: "2026-01-08T12:00:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9014-alteration",
      orderId: "order-9014",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 2, 17, 0)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9015-custom",
      orderId: "order-9015",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 5, 14, 0)),
      readyAt: null,
      eventId: "event-ethan-prom",
      appointmentOptional: true,
    },
    {
      id: "scope-9016-alteration",
      orderId: "order-9016",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 1, 16, 45)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 11, 50)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9016-custom",
      orderId: "order-9016",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 4, 13, 30)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9017-alteration",
      orderId: "order-9017",
      workflow: "alteration",
      phase: "ready",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 0, 18, 15)),
      readyAt: toDateTimeString(withOffset(baseDate, 0, 12, 30)),
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9018-custom",
      orderId: "order-9018",
      workflow: "custom",
      phase: "picked_up",
      promisedReadyAt: "2026-02-27T17:00:00",
      readyAt: "2026-02-26T14:40:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9019-alteration",
      orderId: "order-9019",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 1, 13, 15)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9019-custom",
      orderId: "order-9019",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 6, 16, 0)),
      readyAt: null,
      eventId: "event-malik-wedding",
      appointmentOptional: true,
    },
    {
      id: "scope-9020-alteration",
      orderId: "order-9020",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withMinuteDelta(liveReference, 210)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9021-custom",
      orderId: "order-9021",
      workflow: "custom",
      phase: "picked_up",
      promisedReadyAt: "2026-02-20T17:15:00",
      readyAt: "2026-02-19T14:10:00",
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9022-alteration",
      orderId: "order-9022",
      workflow: "alteration",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 2, 15, 45)),
      readyAt: null,
      eventId: null,
      appointmentOptional: true,
    },
    {
      id: "scope-9023-custom",
      orderId: "order-9023",
      workflow: "custom",
      phase: "in_progress",
      promisedReadyAt: toDateTimeString(withOffset(baseDate, 3, 16, 45)),
      readyAt: null,
      eventId: "event-benjamin-gala",
      appointmentOptional: true,
    },
  ];
}

export function createOrderScopeLines(): DbOrderScopeLine[] {
  return [
    { id: "line-9001-1", scopeId: "scope-9001-custom", label: "Two-piece suit", quantity: 1, unitPrice: 1495 },
    { id: "line-9002-1", scopeId: "scope-9002-alteration", label: "Dress hem", quantity: 1, unitPrice: 240 },
    { id: "line-9002-2", scopeId: "scope-9002-alteration", label: "Vest waist suppression", quantity: 1, unitPrice: 107.8 },
    { id: "line-9003-1", scopeId: "scope-9003-alteration", label: "Trouser taper", quantity: 1, unitPrice: 120 },
    { id: "line-9003-2", scopeId: "scope-9003-custom", label: "Dinner jacket", quantity: 1, unitPrice: 1495 },
    { id: "line-9003-3", scopeId: "scope-9003-custom", label: "Vest", quantity: 1, unitPrice: 741.85 },
    { id: "line-9004-1", scopeId: "scope-9004-alteration", label: "Pant hem", quantity: 1, unitPrice: 54.45 },
    { id: "line-9005-1", scopeId: "scope-9005-alteration", label: "Rush sleeve adjustment", quantity: 1, unitPrice: 95 },
    { id: "line-9006-1", scopeId: "scope-9006-custom", label: "Dinner jacket", quantity: 1, unitPrice: 1495 },
    { id: "line-9007-1", scopeId: "scope-9007-alteration", label: "Skirt hem", quantity: 1, unitPrice: 65 },
    { id: "line-9008-1", scopeId: "scope-9008-custom", label: "Wedding tuxedo", quantity: 1, unitPrice: 1895 },
    { id: "line-9009-1", scopeId: "scope-9009-alteration", label: "Jacket suppression", quantity: 1, unitPrice: 85 },
    { id: "line-9009-2", scopeId: "scope-9009-alteration", label: "Sleeve shorten", quantity: 1, unitPrice: 55 },
    { id: "line-9010-1", scopeId: "scope-9010-alteration", label: "Blouse sleeve taper", quantity: 1, unitPrice: 72 },
    { id: "line-9010-2", scopeId: "scope-9010-custom", label: "Reception jacket", quantity: 1, unitPrice: 1295 },
    { id: "line-9011-1", scopeId: "scope-9011-custom", label: "Mother-of-the-bride suit", quantity: 1, unitPrice: 1595 },
    { id: "line-9012-1", scopeId: "scope-9012-alteration", label: "Stage pant hem", quantity: 1, unitPrice: 45 },
    { id: "line-9012-2", scopeId: "scope-9012-alteration", label: "Jacket sleeve shorten", quantity: 1, unitPrice: 65 },
    { id: "line-9013-1", scopeId: "scope-9013-custom", label: "Black-tie tuxedo", quantity: 1, unitPrice: 1695 },
    { id: "line-8821-1", scopeId: "scope-8821-custom", label: "Custom navy suit", quantity: 1, unitPrice: 1495 },
    { id: "line-8610-1", scopeId: "scope-8610-alteration", label: "Trouser hem + taper", quantity: 1, unitPrice: 65 },
    { id: "line-8443-1", scopeId: "scope-8443-custom", label: "Dinner jacket consult", quantity: 1, unitPrice: 0 },
    { id: "line-8904-1", scopeId: "scope-8904-alteration", label: "Wedding party alteration set", quantity: 1, unitPrice: 320 },
    { id: "line-8904-2", scopeId: "scope-8904-custom", label: "Wedding jacket", quantity: 1, unitPrice: 0 },
    { id: "line-8732-1", scopeId: "scope-8732-alteration", label: "Bridesmaid dress fitting", quantity: 1, unitPrice: 95 },
    { id: "line-8940-1", scopeId: "scope-8940-alteration", label: "Rush suit sleeve adjustment", quantity: 1, unitPrice: 80 },
    { id: "line-8528-1", scopeId: "scope-8528-alteration", label: "Pant waist suppression", quantity: 1, unitPrice: 35 },
    { id: "line-9014-1", scopeId: "scope-9014-alteration", label: "Dress bustle", quantity: 1, unitPrice: 110 },
    { id: "line-9014-2", scopeId: "scope-9014-alteration", label: "Waist take-in", quantity: 1, unitPrice: 65 },
    { id: "line-9015-1", scopeId: "scope-9015-custom", label: "Prom tuxedo", quantity: 1, unitPrice: 1595 },
    { id: "line-9016-1", scopeId: "scope-9016-alteration", label: "Bridesmaid hem", quantity: 1, unitPrice: 140 },
    { id: "line-9016-2", scopeId: "scope-9016-custom", label: "Dinner jacket", quantity: 1, unitPrice: 1325 },
    { id: "line-9017-1", scopeId: "scope-9017-alteration", label: "Suit suppression", quantity: 1, unitPrice: 95 },
    { id: "line-9017-2", scopeId: "scope-9017-alteration", label: "Trouser hem", quantity: 1, unitPrice: 55 },
    { id: "line-9018-1", scopeId: "scope-9018-custom", label: "Midnight tuxedo", quantity: 1, unitPrice: 1795 },
    { id: "line-9019-1", scopeId: "scope-9019-alteration", label: "Trouser taper", quantity: 1, unitPrice: 85 },
    { id: "line-9019-2", scopeId: "scope-9019-custom", label: "Ceremony suit", quantity: 1, unitPrice: 1695 },
    { id: "line-9020-1", scopeId: "scope-9020-alteration", label: "Gown shoulder lift", quantity: 1, unitPrice: 125 },
    { id: "line-9021-1", scopeId: "scope-9021-custom", label: "Charcoal suit", quantity: 1, unitPrice: 1495 },
    { id: "line-9022-1", scopeId: "scope-9022-alteration", label: "Sari blouse adjustment", quantity: 1, unitPrice: 90 },
    { id: "line-9023-1", scopeId: "scope-9023-custom", label: "Dinner suit", quantity: 1, unitPrice: 1545 },
  ];
}

export function createPayments({ baseDate }: RuntimeSeedDates): DbPaymentRecord[] {
  return [
    {
      id: "pay-9001",
      orderId: "order-9001",
      source: "square",
      status: "captured",
      amount: 747.5,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 10, 0)),
      squarePaymentId: "sq_pay_9001",
    },
    {
      id: "pay-9002",
      orderId: "order-9002",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9003",
      orderId: "order-9003",
      source: "square",
      status: "captured",
      amount: 1080,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 11, 30)),
      squarePaymentId: "sq_pay_9003",
    },
    {
      id: "pay-9004",
      orderId: "order-9004",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9005",
      orderId: "order-9005",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9006",
      orderId: "order-9006",
      source: "square",
      status: "captured",
      amount: 747.5,
      collectedAt: toDateTimeString(withOffset(baseDate, 0, 10, 30)),
      squarePaymentId: "sq_pay_9006",
    },
    {
      id: "pay-9007",
      orderId: "order-9007",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9008",
      orderId: "order-9008",
      source: "square",
      status: "captured",
      amount: 950,
      collectedAt: toDateTimeString(withOffset(baseDate, -4, 14, 0)),
      squarePaymentId: "sq_pay_9008",
    },
    {
      id: "pay-9009",
      orderId: "order-9009",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9010",
      orderId: "order-9010",
      source: "square",
      status: "captured",
      amount: 600,
      collectedAt: toDateTimeString(withOffset(baseDate, -6, 10, 45)),
      squarePaymentId: "sq_pay_9010",
    },
    {
      id: "pay-9011",
      orderId: "order-9011",
      source: "square",
      status: "captured",
      amount: 800,
      collectedAt: toDateTimeString(withOffset(baseDate, -3, 12, 0)),
      squarePaymentId: "sq_pay_9011",
    },
    {
      id: "pay-9012",
      orderId: "order-9012",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9013",
      orderId: "order-9013",
      source: "square",
      status: "captured",
      amount: 1695,
      collectedAt: "2026-02-26T15:00:00",
      squarePaymentId: "sq_pay_9013",
    },
    {
      id: "pay-8821",
      orderId: "order-8821",
      source: "square",
      status: "captured",
      amount: 1495,
      collectedAt: "2026-02-28T14:00:00",
      squarePaymentId: "sq_pay_8821",
    },
    {
      id: "pay-8610",
      orderId: "order-8610",
      source: "square",
      status: "captured",
      amount: 65,
      collectedAt: "2026-01-17T12:00:00",
      squarePaymentId: "sq_pay_8610",
    },
    {
      id: "pay-8443",
      orderId: "order-8443",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8904",
      orderId: "order-8904",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8732",
      orderId: "order-8732",
      source: "square",
      status: "captured",
      amount: 95,
      collectedAt: "2026-02-12T13:30:00",
      squarePaymentId: "sq_pay_8732",
    },
    {
      id: "pay-8940",
      orderId: "order-8940",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-8528",
      orderId: "order-8528",
      source: "square",
      status: "captured",
      amount: 35,
      collectedAt: "2026-01-08T12:00:00",
      squarePaymentId: "sq_pay_8528",
    },
    {
      id: "pay-9014",
      orderId: "order-9014",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9015",
      orderId: "order-9015",
      source: "square",
      status: "captured",
      amount: 800,
      collectedAt: toDateTimeString(withOffset(baseDate, -3, 15, 30)),
      squarePaymentId: "sq_pay_9015",
    },
    {
      id: "pay-9016",
      orderId: "order-9016",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9017",
      orderId: "order-9017",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9018",
      orderId: "order-9018",
      source: "square",
      status: "captured",
      amount: 1795,
      collectedAt: "2026-02-26T14:10:00",
      squarePaymentId: "sq_pay_9018",
    },
    {
      id: "pay-9019",
      orderId: "order-9019",
      source: "square",
      status: "captured",
      amount: 900,
      collectedAt: toDateTimeString(withOffset(baseDate, -2, 16, 35)),
      squarePaymentId: "sq_pay_9019",
    },
    {
      id: "pay-9020",
      orderId: "order-9020",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9021",
      orderId: "order-9021",
      source: "square",
      status: "captured",
      amount: 1495,
      collectedAt: "2026-02-19T14:05:00",
      squarePaymentId: "sq_pay_9021",
    },
    {
      id: "pay-9022",
      orderId: "order-9022",
      source: "prototype",
      status: "due_later",
      amount: 0,
      collectedAt: null,
      squarePaymentId: null,
    },
    {
      id: "pay-9023",
      orderId: "order-9023",
      source: "square",
      status: "captured",
      amount: 750,
      collectedAt: toDateTimeString(withOffset(baseDate, -5, 14, 30)),
      squarePaymentId: "sq_pay_9023",
    },
  ];
}

export function createSquareLinks(orders: DbOrder[]): DbSquareLink[] {
  return orders.map((order) => ({
    orderId: order.id,
    squareOrderId: `sq_order_${order.displayId.toLowerCase()}`,
  }));
}
