import type {
  DbPickupAppointment,
  DbPickupNotification,
  DbServiceAppointment,
} from "../schema";
import {
  createLocationId,
  RuntimeSeedDates,
  toDateTimeString,
  withOffset,
} from "./support";

export function createPickupNotifications({ baseDate }: RuntimeSeedDates): DbPickupNotification[] {
  return [
    {
      id: "notify-9002-1",
      scopeId: "scope-9002-alteration",
      channel: "sms",
      status: "sent",
      sentAt: toDateTimeString(withOffset(baseDate, 0, 13, 30)),
      note: "Ready message sent; customer may pick up any time today.",
    },
    {
      id: "notify-9003-1",
      scopeId: "scope-9003-alteration",
      channel: "phone",
      status: "requested_pickup",
      sentAt: toDateTimeString(withOffset(baseDate, -1, 9, 0)),
      note: "Customer asked to be called once the custom scope is ready so both pieces can be collected together.",
    },
    {
      id: "notify-8940-1",
      scopeId: "scope-8940-alteration",
      channel: "sms",
      status: "acknowledged",
      sentAt: "2026-03-14T12:30:00",
      note: "Customer confirmed they will pick up after work.",
    },
    {
      id: "notify-9010-1",
      scopeId: "scope-9010-alteration",
      channel: "sms",
      status: "requested_pickup",
      sentAt: toDateTimeString(withOffset(baseDate, 0, 11, 20)),
      note: "Alteration scope is ready, but customer wants to collect once the custom jacket is complete.",
    },
    {
      id: "notify-9011-1",
      scopeId: "scope-9011-custom",
      channel: "email",
      status: "sent",
      sentAt: toDateTimeString(withOffset(baseDate, -1, 16, 45)),
      note: "Fabric approval sent with event deadline reminder.",
    },
  ];
}

export function createPickupAppointments({ baseDate }: RuntimeSeedDates): DbPickupAppointment[] {
  return [
    {
      id: "pickup-1003",
      orderId: "order-9003",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1116",
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 14, 15)),
      locationId: createLocationId("Long Island"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: jeans, pants • Custom: shirt",
      prepStatus: "needs_profile",
      profileFlags: ["missing_phone"],
      contextFlags: [],
    },
    {
      id: "pickup-1006",
      orderId: "order-9002",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1078",
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 16, 0)),
      locationId: createLocationId("Fifth Avenue"),
      source: "manual",
      durationMinutes: 30,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: dress, vest • Custom: jacket",
      prepStatus: "needs_materials",
      profileFlags: [],
      contextFlags: [],
    },
    {
      id: "pickup-1009",
      orderId: "order-9004",
      scopeId: null,
      scopeLineId: null,
      customerId: null,
      scheduledFor: toDateTimeString(withOffset(baseDate, 10, 13, 0)),
      locationId: createLocationId("Long Island"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: pants, shirt",
      prepStatus: "needs_review",
      profileFlags: [],
      contextFlags: [],
    },
    {
      id: "pickup-1010",
      orderId: "order-9010",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1149",
      scheduledFor: toDateTimeString(withOffset(baseDate, 4, 17, 15)),
      locationId: createLocationId("Fifth Avenue"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: blouse sleeve taper • Custom: reception jacket",
      prepStatus: "needs_materials",
      profileFlags: [],
      contextFlags: [],
    },
  ];
}

export function createServiceAppointments({ baseDate }: RuntimeSeedDates): DbServiceAppointment[] {
  return [
    {
      id: "APT-1001",
      customerId: "C-1078",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Maria Ellis",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 9, 30)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "ready_to_check_in",
      prepStatus: "needs_profile",
      profileFlags: ["missing_email"],
      contextFlags: ["confirmed"],
    },
    {
      id: "APT-1002",
      customerId: "C-1042",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "James Carter",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 11, 0)),
      source: "square",
      durationMinutes: 60,
      typeKey: "custom_consult",
      statusKey: "scheduled",
      prepStatus: "ready",
      profileFlags: [],
      contextFlags: ["confirmed"],
    },
    {
      id: "APT-1004",
      customerId: "C-1124",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Andrea Brooks",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 10, 0)),
      source: "square",
      durationMinutes: 45,
      typeKey: "first_fitting",
      statusKey: "prep_required",
      prepStatus: "needs_measurements",
      profileFlags: [],
      contextFlags: [],
    },
    {
      id: "APT-1005",
      customerId: "C-1135",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Noah Bennett",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 13, 30)),
      source: "square",
      durationMinutes: 60,
      typeKey: "custom_consult",
      statusKey: "scheduled",
      prepStatus: "needs_materials",
      profileFlags: [],
      contextFlags: [],
    },
    {
      id: "APT-1007",
      customerId: "C-1116",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "David Nguyen",
      workflow: "alteration",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 4, 12, 0)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      prepStatus: "ready",
      profileFlags: [],
      contextFlags: [],
    },
    {
      id: "APT-1008",
      customerId: "C-1042",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "James Carter",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 7, 15, 30)),
      source: "square",
      durationMinutes: 45,
      typeKey: "custom_fitting",
      statusKey: "scheduled",
      prepStatus: "needs_review",
      profileFlags: [],
      contextFlags: ["confirmed"],
    },
    {
      id: "APT-1009",
      customerId: "C-1149",
      orderId: "order-9010",
      scopeId: "scope-9010-custom",
      scopeLineId: null,
      customerName: "Priya Shah",
      workflow: "custom",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 2, 10, 30)),
      source: "square",
      durationMinutes: 120,
      typeKey: "wedding_party_fitting",
      statusKey: "scheduled",
      prepStatus: "needs_review",
      profileFlags: [],
      contextFlags: ["wedding"],
    },
    {
      id: "APT-1010",
      customerId: "C-1162",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Elena Morales",
      workflow: "alteration",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 11, 15)),
      source: "square",
      durationMinutes: 120,
      typeKey: "wedding_party_fitting",
      statusKey: "prep_required",
      prepStatus: "needs_review",
      profileFlags: [],
      contextFlags: ["wedding"],
    },
    {
      id: "APT-1011",
      customerId: "C-1177",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Marcus Reed",
      workflow: "alteration",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 2, 14, 0)),
      source: "square",
      durationMinutes: 45,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      prepStatus: "needs_review",
      profileFlags: [],
      contextFlags: ["rush"],
    },
  ];
}
