import type {
  DbPickupAppointment,
  DbPickupNotification,
  DbServiceAppointment,
} from "../schema";
import {
  createLocationId,
  RuntimeSeedDates,
  toDateTimeString,
  withOffset,
} from "./support";

export function createPickupNotifications({ baseDate }: RuntimeSeedDates): DbPickupNotification[] {
  return [
    {
      id: "notify-9002-1",
      scopeId: "scope-9002-alteration",
      channel: "sms",
      status: "sent",
      sentAt: toDateTimeString(withOffset(baseDate, 0, 13, 30)),
      note: "Ready message sent; customer may pick up any time today.",
    },
    {
      id: "notify-9003-1",
      scopeId: "scope-9003-alteration",
      channel: "phone",
      status: "requested_pickup",
      sentAt: toDateTimeString(withOffset(baseDate, -1, 9, 0)),
      note: "Customer asked to be called once the custom scope is ready so both pieces can be collected together.",
    },
    {
      id: "notify-8940-1",
      scopeId: "scope-8940-alteration",
      channel: "sms",
      status: "acknowledged",
      sentAt: "2026-03-14T12:30:00",
      note: "Customer confirmed they will pick up after work.",
    },
    {
      id: "notify-9010-1",
      scopeId: "scope-9010-alteration",
      channel: "sms",
      status: "requested_pickup",
      sentAt: toDateTimeString(withOffset(baseDate, 0, 11, 20)),
      note: "Alteration scope is ready, but customer wants to collect once the custom jacket is complete.",
    },
    {
      id: "notify-9011-1",
      scopeId: "scope-9011-custom",
      channel: "email",
      status: "sent",
      sentAt: toDateTimeString(withOffset(baseDate, -1, 16, 45)),
      note: "Fabric approval sent with event deadline reminder.",
    },
    {
      id: "notify-9017-1",
      scopeId: "scope-9017-alteration",
      channel: "sms",
      status: "sent",
      sentAt: toDateTimeString(withOffset(baseDate, 0, 12, 50)),
      note: "Ready pickup message sent for same-day suit adjustments.",
    },
    {
      id: "notify-9018-1",
      scopeId: "scope-9018-custom",
      channel: "email",
      status: "acknowledged",
      sentAt: "2026-02-26T10:15:00",
      note: "Customer confirmed final pickup slot after fitting photos were approved.",
    },
    {
      id: "notify-9023-1",
      scopeId: "scope-9023-custom",
      channel: "phone",
      status: "requested_pickup",
      sentAt: toDateTimeString(withOffset(baseDate, 1, 14, 10)),
      note: "Customer requested a callback once the gala suit is cleared for pickup.",
    },
  ];
}

export function createPickupAppointments({ baseDate }: RuntimeSeedDates): DbPickupAppointment[] {
  return [
    {
      id: "pickup-1003",
      orderId: "order-9003",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1116",
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 14, 15)),
      locationId: createLocationId("Long Island"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: jeans, pants • Custom: shirt",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "pickup-1006",
      orderId: "order-9002",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1078",
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 16, 0)),
      locationId: createLocationId("Fifth Avenue"),
      source: "manual",
      durationMinutes: 30,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: dress, vest • Custom: jacket",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "pickup-1009",
      orderId: "order-9004",
      scopeId: null,
      scopeLineId: null,
      customerId: null,
      scheduledFor: toDateTimeString(withOffset(baseDate, 10, 13, 0)),
      locationId: createLocationId("Long Island"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: pants, shirt",
      confirmationStatus: null,
      rush: false,
    },
    {
      id: "pickup-1010",
      orderId: "order-9010",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1149",
      scheduledFor: toDateTimeString(withOffset(baseDate, 4, 17, 15)),
      locationId: createLocationId("Fifth Avenue"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: blouse sleeve taper • Custom: reception jacket",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "pickup-1011",
      orderId: "order-9017",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1226",
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 18, 0)),
      locationId: createLocationId("Fifth Avenue"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: suit suppression, trouser hem",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "pickup-1012",
      orderId: "order-9016",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1214",
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 14, 30)),
      locationId: createLocationId("Queens"),
      source: "manual",
      durationMinutes: 20,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Alterations: bridesmaid hem • Custom: dinner jacket",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "pickup-1013",
      orderId: "order-9023",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1317",
      scheduledFor: toDateTimeString(withOffset(baseDate, 2, 17, 0)),
      locationId: createLocationId("Queens"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Custom: dinner suit",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "pickup-1014",
      orderId: "order-9018",
      scopeId: null,
      scopeLineId: null,
      customerId: "C-1238",
      scheduledFor: "2026-02-27T16:30:00",
      locationId: createLocationId("Queens"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "completed",
      summary: "Custom: midnight tuxedo",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "pickup-1015",
      orderId: "order-9024",
      scopeId: "scope-9024-custom",
      scopeLineId: null,
      customerId: "C-1325",
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 15, 45)),
      locationId: createLocationId("Fifth Avenue"),
      source: "manual",
      durationMinutes: 15,
      typeKey: "pickup",
      statusKey: "scheduled",
      summary: "Custom: wedding suit",
      confirmationStatus: "confirmed",
      rush: false,
    },
  ];
}

export function createServiceAppointments({ baseDate }: RuntimeSeedDates): DbServiceAppointment[] {
  return [
    {
      id: "APT-1001",
      customerId: "C-1078",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Maria Ellis",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 9, 30)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "ready_to_check_in",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1002",
      customerId: "C-1042",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "James Carter",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 11, 0)),
      source: "square",
      durationMinutes: 60,
      typeKey: "custom_consult",
      statusKey: "scheduled",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "APT-1004",
      customerId: "C-1124",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Andrea Brooks",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 10, 0)),
      source: "square",
      durationMinutes: 45,
      typeKey: "first_fitting",
      statusKey: "prep_required",
      confirmationStatus: null,
      rush: false,
    },
    {
      id: "APT-1005",
      customerId: "C-1135",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Noah Bennett",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 13, 30)),
      source: "square",
      durationMinutes: 60,
      typeKey: "custom_consult",
      statusKey: "scheduled",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "APT-1007",
      customerId: "C-1116",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "David Nguyen",
      workflow: "alteration",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 4, 12, 0)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1008",
      customerId: "C-1042",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "James Carter",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 7, 15, 30)),
      source: "square",
      durationMinutes: 45,
      typeKey: "custom_fitting",
      statusKey: "scheduled",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1009",
      customerId: "C-1149",
      orderId: "order-9010",
      scopeId: "scope-9010-custom",
      scopeLineId: null,
      customerName: "Priya Shah",
      workflow: "custom",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 2, 10, 30)),
      source: "square",
      durationMinutes: 120,
      typeKey: "wedding_party_fitting",
      statusKey: "scheduled",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1010",
      customerId: "C-1162",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Elena Morales",
      workflow: "alteration",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 11, 15)),
      source: "square",
      durationMinutes: 120,
      typeKey: "wedding_party_fitting",
      statusKey: "prep_required",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1011",
      customerId: "C-1177",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Marcus Reed",
      workflow: "alteration",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 14, 0)),
      source: "square",
      durationMinutes: 45,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      confirmationStatus: "unconfirmed",
      rush: true,
    },
    {
      id: "APT-1012",
      customerId: "C-1191",
      orderId: "order-9014",
      scopeId: "scope-9014-alteration",
      scopeLineId: null,
      customerName: "Olivia Chen",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 10, 15)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1013",
      customerId: "C-1203",
      orderId: "order-9015",
      scopeId: "scope-9015-custom",
      scopeLineId: null,
      customerName: "Ethan Ross",
      workflow: "custom",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 12, 30)),
      source: "square",
      durationMinutes: 60,
      typeKey: "first_fitting",
      statusKey: "prep_required",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "APT-1014",
      customerId: "C-1214",
      orderId: "order-9016",
      scopeId: "scope-9016-alteration",
      scopeLineId: null,
      customerName: "Lily Park",
      workflow: "alteration",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 15, 0)),
      source: "square",
      durationMinutes: 45,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      confirmationStatus: "unconfirmed",
      rush: true,
    },
    {
      id: "APT-1015",
      customerId: "C-1259",
      orderId: "order-9020",
      scopeId: "scope-9020-alteration",
      scopeLineId: null,
      customerName: "Harper Cole",
      workflow: "alteration",
      locationId: createLocationId("Long Island"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 0, 16, 45)),
      source: "square",
      durationMinutes: 45,
      typeKey: "wedding_party_fitting",
      statusKey: "prep_required",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1016",
      customerId: "C-1226",
      orderId: "order-9017",
      scopeId: "scope-9017-alteration",
      scopeLineId: null,
      customerName: "Gabriel Stone",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 9, 15)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "ready_to_check_in",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1017",
      customerId: "C-1238",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Zoe Kim",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 12, 15)),
      source: "square",
      durationMinutes: 60,
      typeKey: "custom_consult",
      statusKey: "scheduled",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "APT-1018",
      customerId: "C-1247",
      orderId: "order-9019",
      scopeId: "scope-9019-custom",
      scopeLineId: null,
      customerName: "Malik Johnson",
      workflow: "custom",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 14, 45)),
      source: "square",
      durationMinutes: 90,
      typeKey: "custom_fitting",
      statusKey: "scheduled",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1019",
      customerId: "C-1282",
      orderId: "order-9022",
      scopeId: "scope-9022-alteration",
      scopeLineId: null,
      customerName: "Ava Patel",
      workflow: "alteration",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 1, 17, 30)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "APT-1020",
      customerId: "C-1317",
      orderId: "order-9023",
      scopeId: "scope-9023-custom",
      scopeLineId: null,
      customerName: "Benjamin Lee",
      workflow: "custom",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 2, 11, 0)),
      source: "square",
      durationMinutes: 75,
      typeKey: "custom_fitting",
      statusKey: "scheduled",
      confirmationStatus: "confirmed",
      rush: false,
    },
    {
      id: "APT-1021",
      customerId: "C-1325",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Tessa Monroe",
      workflow: "custom",
      locationId: createLocationId("Fifth Avenue"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 3, 13, 15)),
      source: "square",
      durationMinutes: 60,
      typeKey: "custom_consult",
      statusKey: "prep_required",
      confirmationStatus: "unconfirmed",
      rush: false,
    },
    {
      id: "APT-1022",
      customerId: "C-1271",
      orderId: null,
      scopeId: null,
      scopeLineId: null,
      customerName: "Victor Ramirez",
      workflow: "alteration",
      locationId: createLocationId("Queens"),
      scheduledFor: toDateTimeString(withOffset(baseDate, 4, 10, 45)),
      source: "square",
      durationMinutes: 30,
      typeKey: "alteration_fitting",
      statusKey: "scheduled",
      confirmationStatus: "confirmed",
      rush: false,
    },
  ];
}
